출처
* 머신러닝 완벽가이드
* [머신러닝 완벽가이드] Chap.9 추천 시스템 : https://prod.velog.io/@yepark/%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D-%EC%99%84%EB%B2%BD%EA%B0%80%EC%9D%B4%EB%93%9C-Chap.9-%EC%B6%94%EC%B2%9C-%EC%8B%9C%EC%8A%A4%ED%85%9C  
https://eda-ai-lab.tistory.com/528
* 추천 시스템 기법 연구동향 분석 : https://www.koreascience.or.kr/article/JAKO201512053817215.pdf , https://diane-space.tistory.com/204
* 잠재 요인 모델의 원리를 이용한 협업 태그 기반 추천 방법 : https://www.koreascience.or.kr/article/JAKO200910348031065.pdf

<img src='https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FqsJbG%2FbtqEO0onLyg%2F7OhkKWeQd80fMM6XYIaUa0%2Fimg.png'>

* 협업 필터링 메모리 기반 : 두 사용자 간의 또는 항목 간의 유사도(Similarity)를 측정하여 가장 유사한 사용자들 또는 항목들의 평가치를 반영하여 추천
* 협업 필터링 모델 기반 : 선형대수(Linear Algebra), 신경망(Neural Network), 군집화(Clustering)등을 기반으로 사전에 모델을 수립하여 추천

# 잠재 요인 협업 필터링
## 잠재 요인 협업 필터링의 이해
* 잠재 요인 협업 필터링은 사용자-아이템 평점 매트릭스 속에 숨어 있는 잠재 요인을 추출해 추천 예측을 할 수 있게 하는 기법
* 대규모 다차원 행렬을 SVD와 같은 차원 감소 기법으로 분해하는 과정에서 잠재 요인을 추출하는데, 이러한 기법을 행렬 분해(Matrix Factorization)이라고 함
* 행렬 분해 기반의 잠재 요인 협업 필터링은 넷플릭스 경연 대회에서 사용되면서 유명해짐
* 잠재 요인모델도 모델 기반의 협업 필터링의 일종이므로 모델을 구축하는 단계에서 많은 시간과 노력이 필요하나, 일단 구축되고 나면 신속한 추천이 가능한 장점을 가짐
* '잠재요인'협업 필터링 알고리즘
<img src='https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FKbAHB%2FbtqF6DRxzk1%2FVDHs3Yn3AfmakVf765ck1K%2Fimg.png'>

    1. '잠재 요인'을 기반으로 다차원 희소 행렬인 사용자-아이템 행렬 데이터를 저차원 밀집 행렬의 사용자-잠재요인 행렬과 아이템-잠재요인 행렬의 전치행렬(즉, 잠재요인-아이템행렬)로 분해
    2. 두 행렬의 내적을 통해 새로운 예측 사용자-아이템 평점 행렬 데이터로 만들어 사용자가 아직 평점을 부여하지 않은 아이템에 대한 예측 평점을 생성하는 것
 
    


# 행렬 분해의 이해
* 행렬 분해란 다차원의 매트릭스를 저차원 매트릭스로 분해하는 기법으로 대표적으로 SVD(Sindgular Vector Decomposition), NMF(Non-Negative Matrix Factorization)등이 있음
<img src='https://media.vlpt.us/images/yepark/post/956f666c-3d58-48f0-9d33-58bdc7f2c7fd/%ED%96%89%EB%A0%AC%EB%B6%84%ED%95%B4.PNG'>
R = P * Q.T

* M: 총 사용자 수
* N: 총 아이템 수
* K: 잠재 요인의 차원 수
* R: M x N 차원의 사용자-아이템 평점 행렬
* P: M x K 차원의 사용자-잠재 요인 행렬
* Q: N x K 차원의 아이템-잠재 요인 행렬
* Q.T : Q매트릭스의 행과 열값을 교환한 전치 행렬

#### example
행렬 내 널(NaN)값을 많이 가지는 고차원 희소 행렬인 R 행렬은 다음 그림과 같이 저차원 밀집 행렬이 P와 Q행렬로 분해될 수 있음
<img src='pic1.PNG'>

$$r_{(u,i)} = p_u * q^t_i$$  
$r_{(u,i)} : 평점데이터$  
$p_u : P행렬에서 u행 사용자의 벡터 $  
$q^t_i : Q행렬의 i행 아이템 벡터의 전치 벡터 $  
<img src='pic2.PNG'>
R행렬의 2행 사용자와 4열 아이템에 해당하는 r(2,4)의 예측값은 2.14x1.36 + 0.08x0.75 로 계산 
<img src='pic3.PNG'>
사용자가 평가하지 않은 아이템(영화)에 대한 평점도 잠재 요인으로 분해된 P행렬과 Q 행렬을 이용해 예측
<img src='pic4.PNG'>
사용자-아이템 평점 행렬의 미정값을 포함한 모든 평점 값은 행렬 분해를 통해 얻어진 P행렬과 Q.T 행렬의 내적을 통해 예측 평점으로 다시 계산

#### R행렬을 어떻게 P와 Q행렬로 분해?
* SVD(Singular Value Decomposition)
    * 주로 SVD 방식을 이용하지만 SVD는 널값이 없는 행렬에만 적용가능
* 사용자-아이템 평점 행렬에는 사용자가 평점을 매기지 않은 널(NaN) 데이터가 많기 때문에 주로 SGD(확률적 경사하강법, Stochastic Gradient Descent), ALS(Alternating Least Squares) 기반의 행렬 분해 이용

# 확률적 경사하강법을 이용한 행렬 분해
* P와 Q행렬로 계산된 예측 R 행렬 값이 실제 R 행렬 값과 가장 최소의 오류를 가질 수 있도록 반복적인 비용 함수 최적화를 통해 P와 Q를 유추해 내는것

### 확률적 경사하강법(SGD)를 이용한 행렬 분해의 절차  
####    1. P와 Q를 임의의 값을 가진 행렬로 설정
####    2. P와 Q.T값을 곱해 예측 R 행렬을 계산하고 예측 R 행렬과 실제 R 행렬에 해당하는 오류 값을 계산
####    3. 이 오류 값을 최소화 할 수 있도록 P와 Q 행렬을 적절한 값으로 각각 업데이트
####    4. 만족할 만한 오류값을 가질때 까지 2,3 번 작업을 반복하면서 P와Q값을 업데이트해 근사화 함
    
### 실제값과 예측값을 오류 최소화와 L2규제(Regularization)를 고려한 비용 함수식  
  
$$min\sum(r_{(u,i)} -p_{u}q^t_{i})^2 + \lambda(\left \Vert q_i\right \|^2 +\left \Vert p_u\right \|^2 )$$
- 사용자-아이템 평점 행렬의 경우 행렬 분해를 위해서 단순히 예측 오류값의 최소화와 학습시 과적합을 피하기 위해서 규제를 반영한 비용 함수를 적용  
- 비용함수를 최소화하기 위해 새롭게 P와Q를 업데이트
$$\acute{p}_u = p_u + \eta(e_{(u,i)}*q_i- \lambda*p_u)$$
$$\acute{q}_i = q_i + \eta(e_{(u,i)}*p_u- \lambda*q_i)$$
$p_u : P행렬의\ 사용자u행 벡터$  
$q^t_{i} : Q행렬의\ 아이템i행의\ 전치\ 벡터(transpose vector)$  
$r_{(u,i)}: 실제R\ 행렬의u행,i열에 위치한 값$  
$\hat{r}_{(u,i)} : 예측 \hat{r}행렬의 u행,i열에\ 위치한\ 값.p_{u}*q^t_{i}$
$e_{(u,i)}: u행,i열에 위치한 실제 행렬 값과 예측 행렬 값의 차이 오류.\ r_{(u,i)}-\hat{r}_{(u,i)}로 계산$  
$\eta: SGD학습률 $  
$\lambda: L2규제(Regularization)계수$  
  

#### L2 규제를 반영해 실제 R행렬값과 예측 R행렬 값의 차이를 최소화 하는 방향성을 가지고 P행렬과 Q 행렬에 업데이트 값을 반복적으로 수행하면서 최적화된 예측 R 행렬을 구하는 방식이 SGD 기반의 행렬 분해

# SGD 행렬분해 파이썬으로 구현

### 원본행렬 R 생성, 분해행렬 P와 Q는 정규 분포를 가진 랜덤 값으로 초기화, 잠재요인3

In [1]:
import numpy as np
# 원본 행렬 R 생성, 분해 행렬 P와 Q 초기화, 잠재 요인 차원 K는 3으로 설정
R=np.array([[4,np.NaN, np.NaN, 2, np.NaN],
           [np.NaN, 5,np.NaN, 3, 1],
           [np.NaN, np.NaN, 3, 4, 4],
           [5,2,1,2,np.NaN]])
print(R)
# shape 행,열 두 개 변수에 할당하기
num_users, num_items = R.shape
print(num_users)
print(num_items)

# 잠재 요인 차원 K는 3
K=3

#P와 Q행렬의 크기를 지정하고 정규 분포를 가진 임의의 값으로 입력
np.random.seed(1) #난수 Seed 생성
# np.random.normal ->  scale: 표준편차, size : 여기서는 array 형태 sample size
P=np.random.normal(scale=1./K, size=(num_users,K)) # P행렬 : 사용자 - 잠재요인 행렬
Q=np.random.normal(scale=1./K, size=(num_items,K)) # Q행렬 : 아이템 - 잠재요인 행렬
print('P:',P)
print('Q:',Q)

[[ 4. nan nan  2. nan]
 [nan  5. nan  3.  1.]
 [nan nan  3.  4.  4.]
 [ 5.  2.  1.  2. nan]]
4
5
P: [[ 0.54144845 -0.2039188  -0.17605725]
 [-0.35765621  0.28846921 -0.76717957]
 [ 0.58160392 -0.25373563  0.10634637]
 [-0.08312346  0.48736931 -0.68671357]]
Q: [[-0.1074724  -0.12801812  0.37792315]
 [-0.36663042 -0.05747607 -0.29261947]
 [ 0.01407125  0.19427174 -0.36687306]
 [ 0.38157457  0.30053024  0.16749811]
 [ 0.30028532 -0.22790929 -0.04096341]]


### 실제 R 행렬과 예측 행렬의 오차를 구하는 get_rmse()함수 만들기

In [2]:
from sklearn.metrics import mean_squared_error

def get_rmse(R,P,Q,non_zeros):
    error=0
    #두 개의 분해된 행렬 P와 Q.T의 내적으로 예측 R 행렬 생성
    full_pred_matrix = np.dot(P, Q.T)
    
    #실제 R 행렬에서 널이 아닌 값의 위치 인덱스를 추출해 실제 R 행렬과 예측 행렬의 RMSE 추출
    x_non_zero_ind = [non_zero[0] for non_zero in non_zeros] #행 위치
    y_non_zero_ind = [non_zero[1] for non_zero in non_zeros] #열 위치
    R_non_zeros = R[x_non_zero_ind, y_non_zero_ind] # 실제 R행렬에서 NaN이 아닌 값의 위치
    full_pred_matrix_non_zeros = full_pred_matrix[x_non_zero_ind, y_non_zero_ind] #예측 R 행렬에서 같은 위치
    mse = mean_squared_error(R_non_zeros, full_pred_matrix_non_zeros)  # 예측값과 실제값의 MSE
    rmse = np.sqrt(mse) #MSE값에 root 씌우기 -> RMSE
    
    return rmse
    

#### steps 1000번 동안 반복 
#### $\acute{p}_u = p_u + \eta(e_{(u,i)}*q_i- \lambda*p_u)$  , $\acute{q}_i = q_i + \eta(e_{(u,i)}*p_u- \lambda*q_i)$ 를 통해새로운 $p_u$,$q_i$값으로 업데이트
#### get_rmse() 함수를 통해 50회 반복할 때마다 오류값 출력

In [3]:
# R에서 널값을 제외한 데이터 행렬 인덱스 추출 : R>0 인 행 위치, 열 위치, 값을 non_zeros 리스트에 저장
non_zeros = [(i,j,R[i,j]) for i in range(num_users) for j in range(num_items) if R[i,j]>0] 
# if에 해당하는 조건만 이중 for문 사용하여 나타냄
print(non_zeros)

steps =1000 # SGD반복해서 업데이트 할 횟수
learning_rate = 0.01 # SGD 학습률
r_lambda=0.01 # L2 Regularization 계수

# SGD 기법으로 P와 Q 매트릭스를 계속 업데이트
for step in range(steps):
    for i,j,r in non_zeros:
        # 실제 값과 예측 값의 차이인 오류 값 구함
        eij = r - np.dot(P[i,:], Q[j,:].T)
        
        # Regularization을 반영한 SGD 업데이트 공식 적용
        P[i,:] = P[i,:] + learning_rate*(eij * Q[j,:]-r_lambda*P[i,:])
        Q[j,:] = Q[j,:] + learning_rate*(eij * P[i,:]-r_lambda*Q[j,:])
        
    rmse = get_rmse(R, P, Q, non_zeros)

    if (step % 50) == 0:
        print('### iteration step: ', step,"rmse:",rmse)

[(0, 0, 4.0), (0, 3, 2.0), (1, 1, 5.0), (1, 3, 3.0), (1, 4, 1.0), (2, 2, 3.0), (2, 3, 4.0), (2, 4, 4.0), (3, 0, 5.0), (3, 1, 2.0), (3, 2, 1.0), (3, 3, 2.0)]
### iteration step:  0 rmse: 3.2388050277987723
### iteration step:  50 rmse: 0.4876723101369648
### iteration step:  100 rmse: 0.1564340384819247
### iteration step:  150 rmse: 0.07455141311978046
### iteration step:  200 rmse: 0.04325226798579314
### iteration step:  250 rmse: 0.029248328780878973
### iteration step:  300 rmse: 0.022621116143829466
### iteration step:  350 rmse: 0.019493636196525135
### iteration step:  400 rmse: 0.018022719092132704
### iteration step:  450 rmse: 0.01731968595344266
### iteration step:  500 rmse: 0.016973657887570753
### iteration step:  550 rmse: 0.016796804595895633
### iteration step:  600 rmse: 0.01670132290188466
### iteration step:  650 rmse: 0.01664473691247669
### iteration step:  700 rmse: 0.016605910068210026
### iteration step:  750 rmse: 0.016574200475705
### iteration step:  800 rms

### P와 Q함수를 P*Q.T로 예측 행렬 만들어서 출력

In [4]:
pred_matrix = np.dot(P,Q.T)
print('예측행렬:\n', np.round(pred_matrix,3))
print('원본행렬:\n', R)

예측행렬:
 [[3.991 0.897 1.306 2.002 1.663]
 [6.696 4.978 0.979 2.981 1.003]
 [6.677 0.391 2.987 3.977 3.986]
 [4.968 2.005 1.006 2.017 1.14 ]]
원본행렬:
 [[ 4. nan nan  2. nan]
 [nan  5. nan  3.  1.]
 [nan nan  3.  4.  4.]
 [ 5.  2.  1.  2. nan]]


#### 원본행렬과 비교해 널이 아닌 값은 큰 차이가 나지 않으며, 널인 값은 새로운 예측값으로 채워졌음

# 행렬 분해를 이용한 잠재 요인 협업 필터링 실습
## 사용자-영화 평점 행렬을 분해하고 영화 추천하는 로직구현
* get_rmse() : 실제 R 행렬과 예측 행렬의 오차를 구하는 함수 
* matrix_factorization() : 행렬 분해 로직
* R : 원본 사용자-아이템 평점 행렬
* K : 잠재 요인의 차원수
* steps : SGD 반복 횟수
* learning_rate : 학습률
* r_lambda : L2규제 계수

In [5]:
def matrix_factorization(R, K, steps=200, learning_rate= 0.01, r_lambda = 0.01):
    num_users, num_items = R.shape
    # P와 Q 매트릭스의 크기를 지정하고 정규 분포를 가진 랜덤한 값으로 입력
    np.random.seed(1)
    P=np.random.normal(scale=1./K, size=(num_users,K)) # P행렬 : 사용자 - 잠재요인 행렬
    Q=np.random.normal(scale=1./K, size=(num_items,K)) # Q행렬 : 아이템 - 잠재요인 행렬
    
    prev_rmse = 10000
    break_count = 0
    
    # R에서 널값을 제외한 데이터 행렬 인덱스 추출 : R>0 인 행 위치, 열 위치, 값을 non_zeros 리스트에 저장
    non_zeros = [(i,j,R[i,j]) for i in range(num_users) for j in range(num_items) if R[i,j]>0] 
    
    # SGD 기법으로 P와 Q 매트릭스를 계속 업데이트
    for step in range(steps):
        for i,j,r in non_zeros:
            # 실제 값과 예측 값의 차이인 오류 값 구함
            eij = r - np.dot(P[i,:], Q[j,:].T)

            # Regularization을 반영한 SGD 업데이트 공식 적용
            P[i,:] = P[i,:] + learning_rate*(eij * Q[j,:]-r_lambda*P[i,:])
            Q[j,:] = Q[j,:] + learning_rate*(eij * P[i,:]-r_lambda*Q[j,:])

        rmse = get_rmse(R, P, Q, non_zeros)

        if (step % 10) == 0:
            print('### iteration step: ', step,"rmse:",rmse)   
    return P, Q

### 영화 평점 행렬 데이터를 새롭게 DataFrame 으로 로딩한 뒤에 다시 사용자-아이템 평점 행렬로 변환

In [24]:
import pandas as pd
import numpy as np

movies = pd.read_csv('./ml-latest-small/movies.csv')
ratings = pd.read_csv('./ml-latest-small/ratings.csv')
ratings = ratings[['userId','movieId','rating']]
# print(movies)
# print(ratings)
rating_matrix = ratings.pivot_table('rating',index='userId',columns='movieId')
# print(rating_matrix)

# #title 칼럼을 얻기 위해 movies와 조인 수행
rating_movies = pd.merge(ratings, movies, on='movieId')

# # columns='title' 로 title 컬럼으로 pivot 수행
ratings_matrix = rating_movies.pivot_table('rating', index='userId', columns='title')

ratings_matrix_df = pd.DataFrame(data=ratings_matrix, index = ratings_matrix.index, columns = ratings_matrix.columns)
ratings_matrix_df.head(3)

title   '71 (2014)  'Hellboy': The Seeds of Creation (2004)  \
userId                                                        
1              NaN                                      NaN   
2              NaN                                      NaN   
3              NaN                                      NaN   

title   'Round Midnight (1986)  'Salem's Lot (2004)  \
userId                                                
1                          NaN                  NaN   
2                          NaN                  NaN   
3                          NaN                  NaN   

title   'Til There Was You (1997)  'Tis the Season for Love (2015)  \
userId                                                               
1                             NaN                              NaN   
2                             NaN                              NaN   
3                             NaN                              NaN   

title   'burbs, The (1989)  'night Mother (1986)  (500) Days of Summer (2009)  \
userId                                                                          
1                      NaN                   NaN                          NaN   
2                      NaN                   NaN                          NaN   
3                      NaN                   NaN                          NaN   

title   *batteries not included (1987)  ...  Zulu (2013)  [REC] (2007)  \
userId                                  ...                              
1                                  NaN  ...          NaN           NaN   
2                                  NaN  ...          NaN           NaN   
3                                  NaN  ...          NaN           NaN   

title   [REC]² (2009)  [REC]³ 3 Génesis (2012)  \
userId                                           
1                 NaN                      NaN   
2                 NaN                      NaN   
3                 NaN                      NaN   

title   anohana: The Flower We Saw That Day - The Movie (2013)  \
userId                                                           
1                                                     NaN        
2                                                     NaN        
3                                                     NaN        

title   eXistenZ (1999)  xXx (2002)  xXx: State of the Union (2005)  \
userId                                                                
1                   NaN         NaN                             NaN   
2                   NaN         NaN                             NaN   
3                   NaN         NaN                             NaN   

title   ¡Three Amigos! (1986)  À nous la liberté (Freedom for Us) (1931)  
userId                                                                    
1                         4.0                                        NaN  
2                         NaN                                        NaN  
3                         NaN                                        NaN  

[3 rows x 9719 columns]

In [7]:
P, Q = matrix_factorization(ratings_matrix.values, K=50, steps=200, learning_rate=0.01,r_lambda = 0.01)
pred_matrix = np.dot(P,Q.T)

### iteration step:  0 rmse: 2.9023619751336867
### iteration step:  10 rmse: 0.7335768591017927
### iteration step:  20 rmse: 0.5115539026853442
### iteration step:  30 rmse: 0.37261628282537446
### iteration step:  40 rmse: 0.2960818299181014
### iteration step:  50 rmse: 0.2520353192341642
### iteration step:  60 rmse: 0.22487503275269854
### iteration step:  70 rmse: 0.20685455302331537
### iteration step:  80 rmse: 0.19413418783028685
### iteration step:  90 rmse: 0.18470082002720403
### iteration step:  100 rmse: 0.17742927527209104
### iteration step:  110 rmse: 0.17165226964707486
### iteration step:  120 rmse: 0.1669518194687172
### iteration step:  130 rmse: 0.16305292191997542
### iteration step:  140 rmse: 0.15976691929679643
### iteration step:  150 rmse: 0.1569598699945732
### iteration step:  160 rmse: 0.15453398186715428
### iteration step:  170 rmse: 0.15241618551077643
### iteration step:  180 rmse: 0.15055080739628307
### iteration step:  190 rmse: 0.1488947091323209

### 예측 사용자- 아이템 평점 행렬을 영화 타이틀을 컬럼명으로 가지는 DataFrame으로 변경

In [8]:
ratings_pred_matrix = pd.DataFrame(data=pred_matrix, index = ratings_matrix.index, columns = ratings_matrix.columns)
ratings_pred_matrix.head(3)

title   '71 (2014)  'Hellboy': The Seeds of Creation (2004)  \
userId                                                        
1         3.055084                                 4.092018   
2         3.170119                                 3.657992   
3         2.307073                                 1.658853   

title   'Round Midnight (1986)  'Salem's Lot (2004)  \
userId                                                
1                     3.564130             4.502167   
2                     3.308707             4.166521   
3                     1.443538             2.208859   

title   'Til There Was You (1997)  'Tis the Season for Love (2015)  \
userId                                                               
1                        3.981215                         1.271694   
2                        4.311890                         1.275469   
3                        2.229486                         0.780760   

title   'burbs, The (1989)  'night Mother (1986)  (500) Days of Summer (2009)  \
userId                                                                          
1                 3.603274              2.333266                     5.091749   
2                 4.237972              1.900366                     3.392859   
3                 1.997043              0.924908                     2.970700   

title   *batteries not included (1987)  ...  Zulu (2013)  [REC] (2007)  \
userId                                  ...                              
1                             3.972454  ...     1.402608      4.208382   
2                             3.647421  ...     0.973811      3.528264   
3                             2.551446  ...     0.520354      1.709494   

title   [REC]² (2009)  [REC]³ 3 Génesis (2012)  \
userId                                           
1            3.705957                 2.720514   
2            3.361532                 2.672535   
3            2.281596                 1.782833   

title   anohana: The Flower We Saw That Day - The Movie (2013)  \
userId                                                           
1                                                2.787331        
2                                                2.404456        
3                                                1.635173        

title   eXistenZ (1999)  xXx (2002)  xXx: State of the Union (2005)  \
userId                                                                
1              3.475076    3.253458                        2.161087   
2              4.232789    2.911602                        1.634576   
3              1.323276    2.887580                        1.042618   

title   ¡Three Amigos! (1986)  À nous la liberté (Freedom for Us) (1931)  
userId                                                                    
1                    4.010495                                   0.859474  
2                    4.135735                                   0.725684  
3                    2.293890                                   0.396941  

[3 rows x 9719 columns]

### 사용자가 이미 평점을 준 영화를 제외하고 추천할 수 있도록 평점을 주지 않은 영화를 리스트 객체로 반환하는 함수 생성

In [9]:
def get_unseen_movies(ratings_matrix, userId):
    # userId로 입력받은 사용자의 모든 영화정보 추출하여 Series로 반환함. 
    # 반환된 user_rating 은 영화명(title)을 index로 가지는 Series 객체임. 
    user_rating = ratings_matrix.loc[userId,:]
    
    # user_rating이 0보다 크면 기존에 관람한 영화임. 대상 index를 추출하여 list 객체로 만듬
    already_seen = user_rating[ user_rating > 0].index.tolist()
    
    # 모든 영화명을 list 객체로 만듬. 
    movies_list = ratings_matrix.columns.tolist()
    
    # list comprehension으로 already_seen에 해당하는 movie는 movies_list에서 제외함. 
    unseen_list = [ movie for movie in movies_list if movie not in already_seen]
    
    return unseen_list

### 최종적으로 사용자에게 영화를 추천하는 함수

In [10]:
def recomm_movie_by_userid(pred_df, userId, unseen_list, top_n=10):
    # 예측 평점 DataFrame에서 사용자id index와 unseen_list로 들어온 영화명 컬럼을 추출하여
    # 가장 예측 평점이 높은 순으로 정렬함. 
    recomm_movies = pred_df.loc[userId, unseen_list].sort_values(ascending=False)[:top_n]
    return recomm_movies

In [11]:
# 사용자가 관람하지 않은 영화명 추출
unseen_list = get_unseen_movies(ratings_matrix, 9)

# 잠재 요인 협업 필터링으로 영화 추천
recomm_movies = recomm_movie_by_userid(ratings_pred_matrix, 9, unseen_list, top_n = 10)

# 평점 데이터를 DataFrame으로 생성.
recomm_movies = pd.DataFrame(data=recomm_movies.values, index=recomm_movies.index, columns=['pred_score'])
recomm_movies

pred_score
title                                                         
Rear Window (1954)                                    5.704612
South Park: Bigger, Longer and Uncut (1999)           5.451100
Rounders (1998)                                       5.298393
Blade Runner (1982)                                   5.244951
Roger & Me (1989)                                     5.191962
Gattaca (1997)                                        5.183179
Ben-Hur (1959)                                        5.130463
Rosencrantz and Guildenstern Are Dead (1990)          5.087375
Big Lebowski, The (1998)                              5.038690
Star Wars: Episode V - The Empire Strikes Back ...    4.989601

In [26]:
rating_movies[rating_movies['userId']==9]

userId  movieId  rating  \
1262        9      223     4.0   
5641        9      923     5.0   
7132        9     1198     5.0   
8727        9     1270     5.0   
10653       9     2012     4.0   
28001       9       41     3.0   
31433       9      371     3.0   
35930       9     4993     5.0   
36251       9     5218     4.0   
36458       9     5378     3.0   
36550       9     5445     4.0   
37032       9     5952     5.0   
39926       9      187     3.0   
39930       9      627     3.0   
39936       9      922     4.0   
39963       9     1037     2.0   
39987       9     1095     4.0   
40002       9     1674     4.0   
40042       9     1987     2.0   
40044       9     2011     3.0   
40131       9     2023     3.0   
40176       9     2300     5.0   
40209       9     2877     3.0   
40216       9     2901     2.0   
40230       9     3173     2.0   
40248       9     3328     3.0   
40267       9     3735     3.0   
40284       9     4131     1.0   
40287       9     4558     1.0   
40301       9     5447     4.0   
40303       9     5451     4.0   
40308       9     5481     5.0   
40373       9     5507     1.0   
40397       9     5841     1.0   
40400       9     5843     3.0   
40404       9     5872     3.0   
40431       9     5890     4.0   
40433       9     5891     1.0   
40437       9     5893     4.0   
40439       9     5902     5.0   
40485       9     5956     4.0   
40540       9     5962     1.0   
40541       9     5965     4.0   
40544       9     5988     2.0   
40548       9     6001     4.0   
40555       9     6044     2.0   

                                                   title  \
1262                                       Clerks (1994)   
5641                                 Citizen Kane (1941)   
7132   Raiders of the Lost Ark (Indiana Jones and the...   
8727                           Back to the Future (1985)   
10653                 Back to the Future Part III (1990)   
28001                                 Richard III (1995)   
31433                                  Paper, The (1994)   
35930  Lord of the Rings: The Fellowship of the Ring,...   
36251                                     Ice Age (2002)   
36458  Star Wars: Episode II - Attack of the Clones (...   
36550                             Minority Report (2002)   
37032      Lord of the Rings: The Two Towers, The (2002)   
39926                                  Party Girl (1995)   
39930                            Last Supper, The (1995)   
39936      Sunset Blvd. (a.k.a. Sunset Boulevard) (1950)   
39963                          Lawnmower Man, The (1992)   
39987                         Glengarry Glen Ross (1992)   
40002                                     Witness (1985)   
40042                                  Prom Night (1980)   
40044                  Back to the Future Part II (1989)   
40131                    Godfather: Part III, The (1990)   
40176                              Producers, The (1968)   
40209                                       Tommy (1975)   
40216                                    Phantasm (1979)   
40230                            Any Given Sunday (1999)   
40248           Ghost Dog: The Way of the Samurai (1999)   
40267                                     Serpico (1973)   
40284                            Making Mr. Right (1987)   
40287                                       Twins (1988)   
40301                              Sunshine State (2002)   
40303                                     Pumpkin (2002)   
40308                 Austin Powers in Goldmember (2002)   
40373                                         xXx (2002)   
40397                   Return to the Blue Lagoon (1991)   
40400                                Toy Soldiers (1991)   
40404                             Die Another Day (2002)   
40431                                      Elling (2001)   
40433     I Spit on Your Grave (Day of the Woman) (1978)   
40437                         Last Seduction, The (1994)   
40439   